### ISSUE TITLE
Malformed morph.ini input results in ctd

### ISSUE THREAD

**Issue by alandtse** [napmouse/autoBodyAE#1]
The following results in a ctd on start.

```
All|Female=- Zeroed Sliders -
```

There probably needs to be some error checking. This specifically crashes here:
https://github.com/napmouse/autoBodyAE/blob/217c9a7ed34191b4199403766ea5e3207d00ed20/src/presetmanager.cpp#L791-L795

I haven't fully debugged it but looks like it may be an array out of bounds.

**Comment by napmouse** [comment]
Absolutely is an array out of bounds. Will add a safety check. Thanks

**Comment by napmouse** [comment]
Fixed with [latest commit.](https://github.com/napmouse/autoBodyAE/commit/b485acda83f5c869dd51ca912ab340650db35a5b)

**Comment by alandtse** [comment]
Thanks that was fast. Just went out to grab dinner and you fixed it.

**Comment by alandtse** [comment]
Btw, noticed a bug for character specifications with the latest fix. 
https://github.com/napmouse/autoBodyAE/pull/3
