### ISSUE TITLE
Feature Request: Options to not clear other morphs

### ISSUE THREAD

**Issue by hex0id** [napmouse/autoBodyAE#22]
It seems autoBody is clearing all morphs before applying its preset. I believe It could be very useful to have an option to filter out some MorphKeys in case there are other mods that affect the body, for example Fertility Mod or user customizations. Can be implemented as a list of MorphKeys to ignore while clearing.

**Comment by hex0id** [comment]
> It seems autoBody is clearing all morphs before applying its preset. 

Oops, I was wrong:
`// finally, clear off any sliders we may have already put on them.
		morphInterface->ClearBodyMorphKeys(a_actor, "autoBody");`

Maybe I messed something up while testing after all :).

**Comment by napmouse** [comment]
The mods base functionality does not clear all the morphs on an actor. The only time autobody should ever do this is when casting the "clear morphs" spell, which I intended mostly as a debug tool for nio morphs in general. The regen spell, menu, and normal generation will only ever clear morphs with autobody keys.
