### ISSUE TITLE
Crash on editing

### ISSUE THREAD

**Issue by CloudtheAngel** [napmouse/autoBodyAE#28]
The game crashes fully when opening the preset menu for my character when I'm playing as a female orc.
If I use the modifier key to use any preset there's no crash (so I suspect it has something to do with races. My morphs.ini has no specified set of presets for any specific race.)
I'm using the DLL compiled for 1.5.97
Here's my autobody.log:
[autoBody.log](https://github.com/napmouse/autoBodyAE/files/8808051/autoBody.log)
Here's my .netscriptframework log if that helps:
[Crash_2022_5_31_20-9-36.txt](https://github.com/napmouse/autoBodyAE/files/8808056/Crash_2022_5_31_20-9-36.txt)

**Comment by napmouse** [comment]
I'm not able to replicate this on my end, and the error its giving in your autobody.log is a catastrophic one which indicates a serious malfunction. Looking at your crash log, your install is absolutely _enormous_, so I would appreciate it if you tried running just the bare minimum and seeing if the crash still appeared. Having that many plugins active makes debugging very difficult, and I suspect this crash arises from a conflict with one of them. It's also possible this is a quirk with SSE, in which case I'm unable to assist.

**Comment by CloudtheAngel** [comment]
Hej, I tried stripping down my load order a bunch and it's still happening. Let me know if I can do any further debugging.
Here's my morhps and config files in case that helps:
[autoBodyConfig.txt](https://github.com/napmouse/autoBodyAE/files/8814238/autoBodyConfig.txt)
[morphs.txt](https://github.com/napmouse/autoBodyAE/files/8814239/morphs.txt)
(They're .txt because github said I couldn't upload .inis)

**Comment by napmouse** [comment]
I'm using your exact morphs.ini and config, and I'm encountering no errors whatsoever. @alandtse are you able to repro this?

**Comment by DustyWantingMicrowave** [comment]
Pretty sure I am running into the same issue too, running the DLL complied for SSE and a morph.ini created by SynthEBD.
Using the modifier key to open the preset menu works fine, 
Opening the preset menu normally for males also worked for me but I don't have any presets or body mesh enabled for males.


Here's some logs/morph.ini if it helps:
[morphs.txt](https://github.com/napmouse/autoBodyAE/files/8885018/morphs.txt)
[autoBody.log](https://github.com/napmouse/autoBodyAE/files/8885022/autoBody.log)
[Crash_2022_6_11_18-46-5.txt](https://github.com/napmouse/autoBodyAE/files/8885023/Crash_2022_6_11_18-46-5.txt)

**Comment by napmouse** [comment]
Finally was able to reproduce this. Thanks for the reports guys, I'll try to fix it ASAP
