### ISSUE TITLE
Only a few Bolt-On presets appearing in-game

### ISSUE THREAD

**Issue by Woolfy123** [napmouse/autoBodyAE#41]
I had AutoBody working perfectly, until I started a new game today. Now I only have a small handful Bolt-On presets appearing and no others loading in, which represent a fraction of what I have enabled and showing as successfully loaded in the AutoBody text file. It says, "124 body presets were loaded into the female master list," yet only six Bolt-On presets show up when I hotkey female NPCs. 

HIMBO and several others successfully load for male NPCs, but despite having all requirements and AutoBody working in a previous run within the last few weeks, female 3BA bodyslides, CBBE, and other derivatives are not appearing. Not even the full slate of Bolt-On presets appear. Reinstalling AutoBody, its requirements, and rerunning Bodyslides changes nothing in-game.

Attached is the debug, which shows six errors whose origins and solutions are unclear to me. Thank you for all your time and help!

Jordan

[autoBody.log](https://github.com/napmouse/autoBodyAE/files/9397948/autoBody.log)

**Comment by napmouse** [comment]
What are the 6 presets that show?

**Comment by Woolfy123** [comment]
Good morning and sorry for the delay! You're able to close this. I
discovered that the cause was this
<https://www.nexusmods.com/skyrimspecialedition/mods/70160>3BA preset on
Nexus. Once this was removed, all other presets began injecting properly
for me. Thank you so much!
