### ISSUE TITLE
Body presets fail to stick when game is saved and loaded. 

### ISSUE THREAD

**Issue by napmouse** [napmouse/autoBodyAE#6]
Repro steps: 
1: apply a body to an NPC.
2: leave the cell the NPC is in
3: save the game 
4: close skyrim and reopen it
5: load that save 
6: enter the cell that NPC was in
you should now see that your NPC no longer has that body applied to them. Checking the log, it appears that autobody is regenerating the actor even when it isn't supposed to. Looks like when returning back to the main menu/closing the game/loading a save, the generated flag (possibly even the entire preset?) is lost from the actor.

**Comment by napmouse** [comment]
Think I know what's causing this. autoBody_processed is possibly not being properly applied. I'll do some testing tomorrow.

**Comment by alandtse** [comment]
It may be worth adding a feature to output generated bodies to a morph.ini. That can then be used to solve this problem too.

**Comment by CeroHY** [comment]
> 
Do you mind posting the process? I am not sure how and where to check if autoBody_processed was being applied.

**Comment by CeroHY** [comment]
> Think I know what's causing this. autoBody_processed is possibly not being properly applied. I'll do some testing tomorrow.

hay @napmouse do you mind sharing how to look for this? I am not sure where to check if autoBody_processed is being applied as it doesn't seem to be in autobody log file.

**Comment by CeroHY** [comment]
@napmouse do you mind if you share the method you used to check if autoBody_processed is applied or not? I have the same issue of things not loading. Thanks in advance.
