### ISSUE TITLE
CTD if Autobody/Config directory does not exist

### ISSUE THREAD

**Issue by alandtse** [napmouse/autoBodyAE#7]
Just got a report for someone manually installing instead of using a mod manager to install.

```OK... actually cleared the CTD by creating the presets folder in autoBody folder as the ini implies (my bad) and putting the presets I'm using in there...```

**Comment by napmouse** [comment]
Should be fixed with fd9dcc0e89b9d316cdd6c2d5a1c73bbb6594af98
