### ISSUE TITLE
Versioning sync

### ISSUE THREAD

**Issue by alandtse** [napmouse/autoBodyAE#9]
Hi @napmouse ,
I just want to coordinate on versioning to the extent possible so if people report things we don't confuse ourselves and we can instantly recognize if they're on your main mod or my port. While I enabled the tweak version, I'd suggest you just use the first 3 numbers per [semantic versioning](https://semver.org/) and leave VR the final tweak version so I can reversion on VR.

So for instance, your last release with the hotfix should have been 1.3.2.0. instead of 1.3.1.1. The feature release would have been 1.4.0.0, etc. If you ever see anything with a nonzero tweak version, you know it was one of my revisions based off your main version. Right now we have a potential collission since my latest VR version is 1.3.1.1 (a vr version of 1.3.1.0). With powerof3, he's just dropping the tweak version entirely when posting on nexus so the only time people see the full version is in the logs.

Does that work for you?

**Comment by napmouse** [comment]
Oh, of course. Sorry, still a little new to semver. I'll stick to the first 3 numbers :)
